ornaments/urls.py
from django.conf.urls import *
from django.urls import include, re_path
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView, ListView, UpdateView, CreateView, DeleteView, TemplateView
from django.db.models import Count
from django.conf import settings
from django.conf.urls.static import static
from ornaments.models import *
from ornaments import views as ornament_views

urlpatterns = [
	re_path(r'^$', ornament_views.OrnamentList.as_view(), name='ornament-list'),
	re_path(r'^ornament/(?P<pk>\d+)/', ornament_views.OrnamentView.as_view(), name='ornament-view'),
	re_path(r'^giver/(?P<pk>\d+)/', ornament_views.GiverView.as_view(), name='giver-view'),
	re_path(r'^receiver/(?P<pk>\d+)/', ornament_views.ReceiverView.as_view(), name='receiver-view'),
	re_path(r'^year/(?P<year>\d+)/$', ornament_views.YearView.as_view(), name='ornament-year')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
from django.conf.urls import *
from django.views.generic import DetailView, ListView, UpdateView, CreateView, DeleteView
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from somesmart.models import *
from somesmart.views import *

admin.autodiscover()

urlpatterns = [
	url(r'^admin/', include(admin.site.urls)),
	url(r'^adventure/', include('adventure.urls')),
	url(r'^cashflow/', include('cashflow.urls')),
	url(r'^lotr/', include('lotr.urls')),
	url(r'^nature/', include('nature.urls')),
	url(r'^ornaments/', include('ornaments.urls')),
	url(r'^kbdb/', include('kbdb.urls')),
	url(r'^', include('somesmart.urls')),
] + staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ornaments/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
import os
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill, Adjust

def get_image_path(instance, filename):
		return os.path.join('photos/ornament', str(instance.year), filename)

class Giver(models.Model):
	id = models.BigAutoField(primary_key=True)
	first_name = models.TextField(max_length=100)
	last_name = models.TextField(max_length=100)

	def __str__(self):
		return "%s %s" % (self.first_name, self.last_name)

class Receiver(models.Model):
	id = models.BigAutoField(primary_key=True)
	first_name = models.TextField(max_length=100)
	last_name = models.TextField(max_length=100)

	def __str__(self):
		return "%s %s" % (self.first_name, self.last_name)

class Ornament(models.Model):
	id = models.BigAutoField(primary_key=True)
	name = models.TextField(max_length=100)
	slug = models.SlugField(null=True, default=None, blank=True)
	giver = models.ForeignKey(Giver, on_delete=models.CASCADE)
	receiver = models.ForeignKey(Receiver, on_delete=models.CASCADE)
	year = models.IntegerField(help_text='The Christmas year the ornament was given')
	notes = models.TextField()
	cloud_location = models.TextField(max_length=250, help_text='The path to the ornament picture in our local cloud storage', null=True, default=None, blank=True)

	image = models.ImageField(upload_to=get_image_path, blank=True)
	image_thumbnail = ImageSpecField([Adjust(contrast=1.2, sharpness=1.1), ResizeToFill(50, 50)], source='image', format='JPEG', options={'quality': 90})
	image_secondary = models.ImageField(upload_to=get_image_path, blank=True)
	image_secondary_thumb = ImageSpecField([Adjust(contrast=1.2, sharpness=1.1), ResizeToFill(50, 50)], source='image', format='JPEG', options={'quality': 90})

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		if not self.id:
			# Newly created object, so set slug
			self.slug = slugify(self.name)

		super(Ornament, self).save(*args, **kwargs)

ornaments/forms.py
from django import forms
from django.forms import ModelForm
from django.forms.models import inlineformset_factory

from ornaments.models import *

ornaments/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect, HttpResponse
import json
from django.db.models import Q, Count, Sum
from django.views.generic import DetailView, ListView, UpdateView, CreateView, FormView
from django.urls import reverse
from django.template import RequestContext
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator
from django.template.defaultfilters import slugify
from ornaments.models import *
from decimal import *
from datetime import datetime
import urllib.request, urllib.error, urllib.parse
from xml.dom.minidom import parseString

# ****************************************************************** #
# *********************** ornament views *************************** #
# ****************************************************************** #

class OrnamentView(DetailView):
	template_name='ornaments/base_ornament.html'
	queryset = Ornament.objects.select_related()

class OrnamentList(ListView):
	template_name='ornaments/base_index.html'
	context_object_name = 'ornament_list'

	def get_queryset(self):
		return Ornament.objects.select_related().filter(year=int(datetime.now().year))

	def get_context_data(self, **kwargs):
		context = super(OrnamentList, self).get_context_data(**kwargs)
		context ['giver_list'] = Giver.objects.all()
		context ['receiver_list'] = Receiver.objects.all()
		return context

class GiverView(DetailView):
	template_name='ornaments/base_giver.html'
	queryset = Giver.objects.select_related()

class ReceiverView(DetailView):
	template_name='ornaments/base_receiver.html'
	queryset = Receiver.objects.select_related()

class YearView(ListView):
	template_name='ornaments/base_year.html'
	context_object_name = 'ornament_list'

	def get_queryset(self):
		return Ornament.objects.select_related().filter(year=self.kwargs['year'])

templates/ornaments/base_giver.html
{% extends "somesmart/base.html" %}
{% block title %}{{ giver }}'s Gifts{% endblock title %}
{% block content %}
	<h3>{{ giver }}'s Gifts</h3>
	{% for ornament in giver.ornament_set.all %}
		<div class="media">
			<a class="media-left pull-left" href="{{ ornament.image.url }}">
				<img src="{{ ornament.image_thumbnail.url }}">
			</a>
			<div class="media-body">
				<h4 class="media-heading"><a href="{% url 'ornament-view' ornament.id %}">{{ ornament.name }}</a> - given to <a href="{% url 'receiver-view' ornament.receiver.id %}{{ ornament.receiver|slugify }}">{{ ornament.receiver }}</a> for Christmas <a href="{% url 'ornament-year' ornament.year %}">{{ ornament.year }}</a></h4>
				{{ ornament.notes }}
			</div>
		</div>
	{% endfor %}
{% endblock content %}
{% block top-right-content %}{% endblock top-right-content %}
{% block right-content %}
	<div class="col-md-10 col-lg-offset-1">
		{% include "somesmart/include_contact.html" %}
	</div>
{% endblock %}

templates/ornaments/base_index.html
{% extends "somesmart/base.html" %}
{% block title %}Ornaments Home Page{% endblock title %}
{% block content %}
	<h3>Givers</h3>
	<ul>
		{% for giver in giver_list %}
			<li><a href="{% url 'giver-view' giver.id %}">{{ giver }}</a></li>
		{% endfor %}
	</ul>
	<h3>Recipients</h3>
	<ul>
		{% for receiver in receiver_list %}
			<li><a href="{% url 'receiver-view' receiver.id %}">{{ receiver }}</a></li>
		{% endfor %}
	</ul>
	<h3>This Year's Ornaments</h3>
	{% for ornament in ornament_list %}
		<div class="media">
			<a class="media-left pull-left" href="{{ ornament.image.url }}">
				<img src="{{ ornament.image_thumbnail.url }}">
			</a>
			<div class="media-body">
				<h4 class="media-heading"><a href="{% url 'ornament-view' ornament.id %}">{{ ornament.name }}</a> - given to <a href="{% url 'receiver-view' ornament.receiver.id %}{{ ornament.receiver|slugify }}">{{ ornament.receiver }}</a></h4>
				{{ ornament.notes }}
			</div>
		</div>
	{% endfor %}
{% endblock content %}
{% block top-right-content %}{% endblock top-right-content %}
{% block right-content %}
	<div class="col-md-10 col-lg-offset-1">
		{% include "somesmart/include_contact.html" %}
	</div>
{% endblock %}

templates/ornaments/base_ornament.html
{% extends "somesmart/base.html" %}
{% block title %}Ornament Page{% endblock title %}
{% block content %}
<a href="{% url 'ornament-list' %}" class="btn btn-default">Back Home</a>
	<h3>{{ ornament.name }}</h3>
	<img src="{{ ornament.image.url }}" class="img-responsive">
	<a href="{{ ornament.image.url }}">Secondary Image</a>
	<p>Given to <a href="{% url 'receiver-view' ornament.receiver.id %}{{ ornament.receiver|slugify }}">{{ ornament.receiver }}</a> by <a href="{% url 'giver-view' ornament.giver.id %}{{ ornament.giver|slugify }}">{{ ornament.giver }}</a> for Christmas <a href="{% url 'ornament-year' ornament.year %}">{{ ornament.year }}</a>
	<p>{{ ornament.description|safe }}</p>
{% endblock content %}
{% block top-right-content %}{% endblock top-right-content %}
{% block right-content %}
	<div class="col-md-10 col-lg-offset-1">
		{% include "somesmart/include_contact.html" %}
	</div>
{% endblock %}

templates/ornaments/base_receiver.html
{% extends "somesmart/base.html" %}
{% block title %}{{ receiver }}'s Ornaments{% endblock title %}
{% block content %}
	<h3>{{ receiver }}'s Ornaments</h3>
	{% for ornament in receiver.ornament_set.all %}
		<div class="media">
			<a class="media-left pull-left" href="{{ ornament.image.url }}">
				<img src="{{ ornament.image_thumbnail.url }}">
			</a>
			<div class="media-body">
				<h4 class="media-heading"><a href="{% url 'ornament-view' ornament.id %}">{{ ornament.name }}</a> - from <a href="{% url 'giver-view' ornament.giver.id %}{{ ornament.giver|slugify }}">{{ ornament.giver }}</a> for Christmas <a href="{% url 'ornament-year' ornament.year %}">{{ ornament.year }}</a></h4>
				{{ ornament.notes }}
			</div>
		</div>
	{% endfor %}
{% endblock content %}
{% block top-right-content %}{% endblock top-right-content %}
{% block right-content %}
	<div class="col-md-10 col-lg-offset-1">
		{% include "somesmart/include_contact.html" %}
	</div>
{% endblock %}

templates/ornaments/base_year.html
{% extends "somesmart/base.html" %}
{% block title %}Ornaments by Year{% endblock title %}
{% block content %}
	{% for ornament in ornament_list %}
		<div class="media">
			<a class="media-left pull-left" href="{{ ornament.image.url }}">
				<img src="{{ ornament.image_thumbnail.url }}">
			</a>
			<div class="media-body">
				<h4 class="media-heading"><a href="{% url 'ornament-view' ornament.id %}">{{ ornament.name }}</a> - given to <a href="{% url 'receiver-view' ornament.receiver.id %}{{ ornament.receiver|slugify }}">{{ ornament.receiver }}</a> by <a href="{% url 'giver-view' ornament.giver.id %}{{ ornament.giver|slugify }}">{{ ornament.giver }}</a> for Christmas <a href="{% url 'ornament-year' ornament.year %}">{{ ornament.year }}</a></h4>
				{{ ornament.notes }}
			</div>
		</div>
	{% endfor %}
{% endblock content %}
{% block top-right-content %}{% endblock top-right-content %}
{% block right-content %}
	<div class="col-md-10 col-lg-offset-1">
		{% include "somesmart/include_contact.html" %}
	</div>
{% endblock %}