somesmart/urls.py
from django.conf.urls import *
from django.urls import include, re_path, path
from django.views.generic import *
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.conf import settings
from django.conf.urls.static import static
from django.db.models import Count
from django.contrib.auth import views as auth_views
from somesmart.models import *
from somesmart import views as somesmart_views
from tagging.views import TaggedObjectList
from wagtail.admin import urls as wagtailadmin_urls
from wagtail import urls as wagtail_urls
from wagtail.documents import urls as wagtaildocs_urls

admin.autodiscover()

urlpatterns = [
	re_path('admin/', admin.site.urls),
	re_path(r'^adventure/', include('adventure.urls')),
	# re_path(r'^cashflow/', include('cashflow.urls')),
	re_path(r'^lotr/', include('lotr.urls')),
	#re_path(r'^nature/', include('nature.urls')),
	re_path(r'^ornaments/', include('ornaments.urls')),
	# re_path(r'^kbdb/', include('kbdb.urls')),
	#re_path(r'^markdownx/', include('markdownx.urls')),
	#re_path(r'^wger/', include('wger.urls')),
	#home page
	re_path(r'^$', somesmart_views.HomePage.as_view(), name= 'home-page'),
		# ListView.as_view(
		# 	queryset=Review.objects.select_related().annotate(reviewed=Count('id')).order_by('-finished')[:10],
		# 	context_object_name='recent_reads',
		# 	template_name='somesmart/base_index.html')),
	#about page
	re_path(r'^about/$', TemplateView.as_view(template_name = 'somesmart/base_about.html'), name='about-page'),
	#book details
	re_path(r'^book/(?P<pk>\d+)/', somesmart_views.BookView.as_view(), name='book-view'),
	re_path(r'^author/(?P<pk>\d+)/', somesmart_views.AuthorView.as_view(), name='author-view'),
	re_path(r'^my-books/$', TemplateView.as_view(template_name = 'somesmart/base_mybooks.html'), name='my-books'),
	#charts
	re_path(r'^charts/$', somesmart_views.GlobalStats.as_view(), name='charts'),
	re_path(r'^charts/(?P<chart>[-\w]+)/(?P<option>[\w\d ]+)$', somesmart_views.ChartGenerate.as_view(), name='chart-generate'),
	re_path(r'^stats/global/$', somesmart_views.get_global_stats, name='global-stats'),
	#quote pages
	re_path(r'^quote/list/$', somesmart_views.QuoteList.as_view(), name='quote-list'),
	re_path(r'^quote/type/(?P<type>\d+)/$',somesmart_views.QuoteTypeList.as_view(), name='quote-type-list'),
	re_path(r'^quote/author/(?P<author>\d+)/',somesmart_views.QuoteAuthorList.as_view(), name='quote-author-list'),
	re_path(r'^quote/book/(?P<book>\d+)/',somesmart_views.QuoteBookList.as_view(), name='quote-book-list'),
	re_path(r'^quote/(?P<pk>\d+)/', somesmart_views.QuoteView.as_view(), name='quote-view'),
	re_path(r'^quote/random/$', somesmart_views.get_random_quote, name='random-quote'),
	#read details
	re_path(r'^review/(?P<pk>\d+)/', somesmart_views.ReviewView.as_view(), name='review-view'),
	re_path(r'^review/book/(?P<pk>\d+)/', somesmart_views.ReviewByBook.as_view(), name='review-by-book'),
	re_path(r'^review/list/$', somesmart_views.ReviewList.as_view(), name='review-list'),
	re_path(r'^review/list/(?P<genre>[-\w]+)/$', somesmart_views.ReviewGenreList.as_view(), name='review-genre-list'),
	#shelf details
	re_path(r'^shelf/(?P<pk>\d+)/', somesmart_views.ShelfView.as_view(), name='shelf-view'),
	#automplete all pass to the same view
	re_path(r'autocomplete/$',somesmart_views.autocomplete, name='autocomplete'),
	re_path(r'gr/current/$', somesmart_views.get_gr_current, name='get-gr-current'),
	#lists
	re_path(r'^list/(?P<pk>\d+)/', somesmart_views.ListDetailView.as_view(), name='list-view'),
	re_path(r'^list/$', somesmart_views.ListSummary.as_view(), name='list-summary'),
	re_path(r'^add/list/$', login_required(somesmart_views.ListCreateView.as_view(template_name='somesmart/base_list_create.html')), name='list-add'),
	re_path(r'^add/list/(?P<list>\d+)/item/(?P<book>\d+)/$', somesmart_views.add_list_item),
	re_path(r'^copy/list/(?P<list>\d+)/$', somesmart_views.copy_list, name='list-copy'),
	re_path(r'^edit/list/(?P<pk>\d+)/$', login_required(somesmart_views.ListUpdate.as_view(template_name='somesmart/base_list_update.html'))),
	re_path(r'^delete/list/item/(?P<pk>\d+)/$', somesmart_views.delete_list_item),
	re_path(r'^delete/list/(?P<pk>\d+)/$', somesmart_views.delete_list),
	#favorites
	re_path(r'^favorites/$', somesmart_views.FavoriteList.as_view(), name='favorite-list'),
	re_path(r'^favorites/(?P<genre>[-\w]+)/$', somesmart_views.FavoriteGenreList.as_view(), name='favorite-genre-list'),
	#tags
	re_path(r'^tags/current/$', somesmart_views.current_tags, name='current-tags'),
	re_path(r'^tags/book/(?P<book>\d+)/$', somesmart_views.book_tags, name='book-tags'),
	re_path(r'^tags/book/(?P<book>\d+)/save/$', somesmart_views.save_tags, name='save-tags'),
	re_path(r'^tags/book/(?P<book>\d+)/related/$', somesmart_views.get_related, name='related-books'),
	re_path(r'^tags/search/(?P<tag>[\w ]+)/$',somesmart_views.TagListView.as_view(), name='search-tags'),
	re_path(r'^tags/cloud/(?P<min_count>\d+)/$', somesmart_views.get_cloud, name='tag-cloud'),
	#the blog
	re_path('pages/feed/', somesmart_views.BlogFeed(), name='rss-feed'),
	re_path('cms/', include(wagtailadmin_urls)),
	re_path('pages/', include(wagtail_urls)),
	# re_path(r'^weblog/', include('zinnia.urls', namespace='zinnia')),
	re_path(r'^comments/', include('django_comments.urls')),
	re_path(r'^contact/', include('django_contact_form.urls')),
	re_path(r'noresults/', TemplateView.as_view(template_name = 'somesmart/base_noresults.html'), name='no-results'),
	#legacy urls
	re_path(r'^books/bookinfo\.php$', somesmart_views.bookinfo_php, name='bookinfo-php'),
	re_path(r'^bookinfo\.php$', somesmart_views.bookinfo_php, name='bookinfo-php'),
	re_path(r'^reviews/$', somesmart_views.bookinfo_php, name='review-old'),
	#malformatted archive links go to the homepage
	re_path(r'^(?P<year>\d{4})/(?P<month>\d{2})/', ListView.as_view(
			queryset=Review.objects.select_related().annotate(reviewed=Count('id')).order_by('-finished')[:10],
			context_object_name='recent_reads',
			template_name='somesmart/base_index.html')),
	# re_path(r'^(?P<year>\d+)/(?P<slug>[-\w]+)/', somesmart_views.zinnia_entry_detail, name='custom-zinnia'),
	# re_path(r'^feeds/$', somesmart_views.zinnia_latest_feeds, name='custom-zinnia-latest'),
	re_path(r'^accounts/login/$', auth_views.LoginView.as_view(), {'template_name': 'somesmart/base_login.html'}, name='account-login'),
	re_path(r'^accounts/logout/$', auth_views.LogoutView.as_view(), {'template_name': 'somesmart/base_logged_out.html'}, name='account-logout'),
	#re_path(r'^todo/', include('todo.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
from django.conf.urls import *
from django.views.generic import DetailView, ListView, UpdateView, CreateView, DeleteView
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from somesmart.models import *
from somesmart.views import *

admin.autodiscover()

urlpatterns = [
	url(r'^admin/', include(admin.site.urls)),
	url(r'^adventure/', include('adventure.urls')),
	url(r'^cashflow/', include('cashflow.urls')),
	url(r'^lotr/', include('lotr.urls')),
	url(r'^nature/', include('nature.urls')),
	url(r'^ornaments/', include('ornaments.urls')),
	url(r'^kbdb/', include('kbdb.urls')),
	url(r'^', include('somesmart.urls')),
] + staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

somesmart/models.py
from django.db import models
from django.urls import reverse
import datetime
from django.contrib.auth import get_user_model
import os
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill, Adjust
from tagging.registry import register

class IntegerRangeField(models.IntegerField):
	id = models.BigAutoField(primary_key=True)
	def __init__(self, verbose_name=None, name=None, min_value=None, max_value=None, **kwargs):
		self.min_value, self.max_value = min_value, max_value
		models.IntegerField.__init__(self, verbose_name, name, **kwargs)
	def formfield(self, **kwargs):
		defaults = {'min_value': self.min_value, 'max_value':self.max_value}
		defaults.update(kwargs)
		return super(IntegerRangeField, self).formfield(**defaults)

class Genre(models.Model):
	id = models.BigAutoField(primary_key=True)
	name = models.TextField(max_length=100)
	slug = models.SlugField()

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		if not self.id:
			# Newly created object, so set slug
			self.slug = slugify(self.name)

		super(Genre, self).save(*args, **kwargs)

class Author(models.Model):
	id = models.BigAutoField(primary_key=True)
	last_name = models.CharField(max_length=200)
	first_name = models.CharField(max_length=200)
	birth_date = models.DateTimeField(null=True, default=None, blank=True)
	death_date = models.DateTimeField(null=True, default=None, blank=True)
	pen_name = models.BooleanField()
	parent_author = models.ForeignKey('self', blank=True, default=None, null=True, help_text='The real name of a pen name', on_delete=models.CASCADE)

	def __str__(self):
		return "%s %s" % (self.first_name, self.last_name)	

class Book(models.Model):
	id = models.AutoField(primary_key=True)
	title = models.CharField(max_length=200)
	author = models.ForeignKey(Author, on_delete=models.CASCADE)
	original_publication = models.DateTimeField()
	synopsis = models.TextField(blank=True)
	reading_age = models.IntegerField()
	content_advisory = models.TextField(blank=True)
	genre = models.ForeignKey(Genre, on_delete=models.CASCADE)

	def __str__(self):
		return self.title

class Edition(models.Model):
	id = models.BigAutoField(primary_key=True)
	def get_image_path(instance, filename):
		return os.path.join('photos/book', str(instance.book.id), filename)

	FORMAT = (
		(1, 'Hardcover'),
		(2, 'Paperback'),
		(3, 'Digital'),
		(4, 'Audio'),
	)

	book = models.ForeignKey(Book, on_delete=models.CASCADE)
	isbn = models.CharField(max_length=20)
	published = models.DateTimeField()
	pages = models.IntegerField()
	format = models.IntegerField(choices=FORMAT)
	cover = models.ImageField(upload_to=get_image_path, blank=True)
	cover_thumbnail = ImageSpecField([Adjust(contrast=1.2, sharpness=1.1), ResizeToFill(50, 50)], source='cover', format='JPEG', options={'quality': 90})
	cover_large = ImageSpecField([Adjust(contrast=1.2, sharpness=1.1), ResizeToFill(333, 500)], source='cover', format='JPEG', options={'quality': 90})
	cover_md = ImageSpecField([Adjust(contrast=1.2, sharpness=1.1), ResizeToFill(100, 170)], source='cover', format='JPEG', options={'quality': 90})

	def __str__(self):
		return "%s - %s" % (self.book.title, self.get_format_display())

class Review(models.Model):
	id = models.BigAutoField(primary_key=True)
	reader = models.ForeignKey(get_user_model(), related_name="+", on_delete=models.CASCADE)
	started = models.DateTimeField()
	finished = models.DateTimeField()
	edition = models.ForeignKey(Edition, on_delete=models.CASCADE)
	critique = models.TextField(blank=True)
	one_sentence = models.CharField(max_length=300, null=True, default=None, blank=True)
	recommend = models.BooleanField()

	def __str__(self):
		return self.one_sentence

#I should consider doing this as a tagging module of some sort. The advantage of having it being "keywords" like this
#is we can also attribute the tag/keyword to the user.
class Keyword(models.Model):
	id = models.BigAutoField(primary_key=True)
	book = models.ForeignKey(Book, on_delete=models.CASCADE)
	reader = models.ForeignKey(get_user_model(), related_name='+', on_delete=models.CASCADE)
	keyword = models.CharField(max_length=100)

class QuoteType(models.Model):
	id = models.BigAutoField(primary_key=True)
	name = models.CharField(max_length=50)
	def __str__(self):
		return self.name

class Quote(models.Model):
	id = models.BigAutoField(primary_key=True)
	edition = models.ForeignKey(Edition, on_delete=models.CASCADE)
	reader = models.ForeignKey(get_user_model(), related_name='+', on_delete=models.CASCADE)
	quote_type = models.ForeignKey(QuoteType, on_delete=models.CASCADE)
	quote = models.TextField()
	page = models.IntegerField()

	def __str__(self):
		return self.quote

class Note(models.Model):
	id = models.BigAutoField(primary_key=True)
	quote = models.ForeignKey(Quote, on_delete=models.CASCADE)
	reader = models.ForeignKey(get_user_model(), related_name='+', on_delete=models.CASCADE)
	note = models.TextField()

	def __str__(self):
		return self.note

class Radar(models.Model):
	id = models.BigAutoField(primary_key=True)
	book = models.ForeignKey(Book, on_delete=models.CASCADE)
	maturity = models.IntegerField()
	violence = models.IntegerField()
	action = models.IntegerField()
	epic = models.IntegerField()
	world = models.IntegerField()
	realism = models.IntegerField()
	modernity = models.IntegerField()
	humor = models.IntegerField()

class Shelf(models.Model):
	id = models.BigAutoField(primary_key=True)
	reader = models.ForeignKey(get_user_model(), related_name='+', on_delete=models.CASCADE)
	name = models.CharField(max_length=100)
	private = models.BooleanField()

	def __str__(self):
		return self.name

class ShelfDetail(models.Model):
	id = models.BigAutoField(primary_key=True)
	shelf = models.ForeignKey(Shelf, on_delete=models.CASCADE)
	book = models.ForeignKey(Book, on_delete=models.CASCADE)

#will probably be able to do this just by pulling in the current status from goodreads
class Currently(models.Model):
	id = models.BigAutoField(primary_key=True)
	edition = models.ForeignKey(Edition, on_delete=models.CASCADE)
	reader = models.ForeignKey(get_user_model(), related_name='+', on_delete=models.CASCADE)
	page = models.IntegerField()

class Favorite(models.Model):
	id = models.BigAutoField(primary_key=True)
	book = models.ForeignKey(Book, on_delete=models.CASCADE)
	user = models.ForeignKey(get_user_model(), related_name='+', on_delete=models.CASCADE)
	rank = models.IntegerField()
	comment = models.TextField()

# ************************************************************** #
# ************************ list data *************************** #
# ************************************************************** #

class List(models.Model):
	id = models.BigAutoField(primary_key=True)
	list_name = models.CharField(max_length=200)
	list_descr = models.CharField(max_length=200)
	user = models.ForeignKey(get_user_model(), related_name="+", on_delete=models.CASCADE) #this is the person who created it, and it will always be here
	def __str__(self):
		return self.list_name
		return "%s - %s" % (self.list_name, self.list_descr)
	def get_absolute_url(self):
		return "/list/%i/" % self.id
	def get_edit_url(self):
		return "/edit/list/%i/" % self.id
	def get_delete_url(self):
		return "/delete/list/%i/" % self.id	
	def get_add_url(self):
		return "/add/list/"

class ListDetail(models.Model):
	id = models.BigAutoField(primary_key=True)
	list = models.ForeignKey(List, related_name="list_details", on_delete=models.CASCADE)
	book = models.ForeignKey(Book, on_delete=models.CASCADE)

# ************************************************************** #
# *********************** series data ************************** #
# ************************************************************** #

class Series(models.Model):
	id = models.BigAutoField(primary_key=True)
	name = models.CharField(max_length=200)
	count = models.IntegerField()

	def __str__(self):
		return self.name

class SeriesDetail(models.Model):
	id = models.BigAutoField(primary_key=True)
	series = models.ForeignKey(Series, on_delete=models.CASCADE)
	book = models.ForeignKey(Book, on_delete=models.CASCADE)
	sequence = models.IntegerField()

	def __str__(self):
		return "%s - %s, %s of %s" % (self.series, self.book, self.sequence, self.series.count)

register(Book)

somesmart/forms.py
from django import forms
from django.forms import ModelForm, Textarea
from django.forms.models import inlineformset_factory
from somesmart.models import *

# ****************************************************************** #
# ********************* course related forms *********************** #
# ****************************************************************** #

class ListForm(ModelForm):
	list_descr = forms.CharField(widget=forms.TextInput(attrs={'size':'60'}))
		
	class Meta:
		model = List
		exclude = ('user',)

	def __init__(self, *args, **kwargs):
		super(ListForm, self).__init__(*args, **kwargs)
		self.fields['list_name'].label = "List Name"
		self.fields['list_descr'].label = "List Description"

class ListDetailForm(ModelForm):
	class Meta:
		model = ListDetail 
		fields = '__all__'

ListDetailFormSet = inlineformset_factory(List, ListDetail, form=ListDetailForm)

templates/somesmart/base_book.html
{% extends "somesmart/base.html" %}
{% load tagging_tags %}
{% load admin_urls %}

{% block title %}{{ book.title }}{% endblock title %}
{% block content %}
	<div>
		<h2>{{ book.title }}
			{# <br><small>by <a href="{% url 'author-view' related.author.id %}">{{ book.author }}</a></small></span></h2> #}
		</h2>
	</div>
	{% if book.synopsis %}
	<h4>Synopsis</h4>
	<div class="row">
		<p class="col-md-5 alert alert-info">This synopsis will contain spoilers!</p>
	</div>
	<div class="review">
		{{ book.synopsis|safe }}
	</div>
	{% endif %}
	<h4>Reviews</h4>
	<dl>
	{% for edition in book.edition_set.all %}
		{% for review in edition.review_set.all %}
			<dt><a href="{% url 'review-view' review.id %}{{ review.edition.book.title|slugify }}">{{ review.edition }}</a>{% if review.recommend %} <i class="bi-hand-thumbs-up" ></i>{% else %} <i class="bi-hand-thumbs-down" ></i>{% endif %}</dt>
			<dd>{% if review.one_sentence %}{{ review.one_sentence|safe }}{% else %}{{ review.critique|truncatewords_html:30|safe }}{% endif %} - {{ review.finished|date }}</dd>
		{% endfor %}
	{% endfor %}
	</dl>
	<h4>Quotes</h4>
	{% for edition in book.edition_set.all %}
		{% for quote in edition.quote_set.all %}
			{% include "somesmart/include_quote.html" %}
		{% endfor %}
	{% endfor %}
	{% if request.user.id == 2 %}
		<a class="btn btn-default float-end" href="{% url 'admin:somesmart_book_change' book.id %}">Edit this book</a>
	{% endif %}
{% endblock content %}
{% block top-right-content %}{% endblock %}
{% block right-content %}
	{% include "somesmart/include_book_data.html" %}
	{% include "somesmart/include_recent_posts.html" %}
	{% include "somesmart/include_book_tags.html" %}
	{% include "somesmart/include_series_data.html" %}
	<div class="row">
		<h4 class="alert alert-secondary">Related Books</h4>
		<div id="related-books"></div>
	</div>
{% endblock %}
{% block app.scripts %}
<script type="text/javascript" src="https://somesmart.com/static/js/tagmanager/bootstrap-tagmanager.js"></script>
<script>
function get_related(book){
	$.ajax({
		type: "GET",
		url: '{% url "related-books" book.id %}',
		success: function(data) {
			$('#related-books').append(data);
		}
	});
 }
 $(function() {
	jQuery(".tagManager").tagsManager({
		prefilled: [{% tags_for_object book as prefilled_tags %}{% for tag in prefilled_tags %}"{{ tag.name }}"{% if not forloop.last %},{% endif %}{% endfor %}],
		preventSubmitOnEnter: true,
		typeahead: true,
		typeaheadAjaxSource: '{% url "current-tags" %}', 
		typeaheadAjaxPolling: false,
		tagClass: 'badge rounded-pill bg-dark'
	});
	{% if request.user.id == 2 %}
	$('.save-tags').click(function() {
		var new_tags = $('input[name=hidden-tagsjax]').val();
		$.ajax({
			url: '{% url "save-tags" book.id %}',
			type: 'POST',
			data: {
			new_tags: new_tags,
			csrfmiddlewaretoken: '{{ csrf_token }}'
			},
			success:function (data) {
			if (data == '1')
			{
				$("#tags-status")
				.addClass("success")
				.html("<div class='alert alert-success'>Your keywords have been saved. <a href='#'' class='close' data-dismiss='alert'>×</a></div>").fadeIn('slow');
			}
			else
			{
				$("#tags-status").addClass("error").html("Error, data could not be saved. Invalid keywords: " + data + " <a href='#'' class='close' data-dismiss='alert'>×</a>").fadeIn('slow');
			}
			}
		});
	});
	{% endif %}
	get_related();
});
</script>
{% endblock %}

templates/somesmart/base_favorite_list.html
{% extends "somesmart/base.html" %}

{% block title %}Favorite Books{% endblock title %}
{% block top-content %}{% endblock %}
{% block content %}
<p class="alert alert-secondary">While you can find various books that I enjoy and recommend from the blog and reviews on the site, searching through all of that can be rather daunting. This page will be an up to date list of my favorite books to read and to recommend by genre. This may also include books I don't yet have a database or blog entry on, but still want to share with others. If you've found that you've read all the books listed in a genre, the rest of the site may be for you!</p>
	{% if favorite_list %}
		{% for favorite in favorite_list %}
		<div class="row py-2">
			<div class="media">
					{% for edition in favorite.book.edition_set.all %}
						{% if forloop.first %}<center>{% if edition.cover %}<img class="media-object float-start" src="{{ edition.cover_md.url }}" width="100px">{% else %}<img data-src="holder.js/100x150/auto" width="100px">{% endif %}</center>{% endif %}
					{% endfor %}
				<div class="media-body">
					<h4 class="media-heading"><a href="{% url 'book-view' favorite.book.id %}{{ favorite.book.title|slugify }}">{{ favorite.book.title }}</a></h4>
					{{ favorite.comment|safe }}
				</div>
			</div>
		</div>
		{% endfor %}
	{% endif %}
	{% include "somesmart/include_pagination.html" %}
{% endblock content %}
{% block app.scripts %}
	<script type="text/javascript" src="https://somesmart.com/static/js/holder/holder.js"></script>
{% endblock %}
{% block right-content %}
	{% if genre_list %}
		<ul class="list-group row">
		{% for genre in genre_list %}
			<li class="list-group-item"><a class="" href="{% url 'favorite-genre-list' genre.book__genre__slug %}">{{ genre.book__genre__name }}</a></li>
		{% endfor %}
		</ul>
	{% endif %}
{% endblock %}

templates/somesmart/base_review.html
{% extends "somesmart/base.html" %}
{% load tagging_tags %}
{% load somesmart_extras %}
{% load admin_urls %}

{% block title %}{{ review.edition.book.title }} Review{% endblock title %}
{% block content %}
	<div>
		<h2>{{ review.edition.book.title }}<br><small>by <a href="{% url 'author-view' review.edition.book.author.id %}">{{ review.edition.book.author }}</a></small></h2>
	</div>
	<h4>A Review by {{ review.reader }} <small>finished {{ review.finished|date }}</small></h4>
	{% if review.one_sentence %}
		<p><strong>In one sentence:</strong> {{ review.one_sentence|safe }}</p>
	{% endif %}
	<div class="row">
		<p class="col-md-5 alert alert-info">This review will contain spoilers!</p>
	</div>
	<p><strong>In many sentences:</strong></p>
	<div class="review">{{ review.critique|safe }}</div>
	{% for quote in review.edition.quote_set.all %}
		<h4>{{ quote.quote_type }}{% if quote.quote_type.id == 1 %} Quote{% endif %}</h4>
		{% include "somesmart/include_quote.html" %}
	{% endfor %}
	{% if request.user.id == review.reader.id %}
		<a class="btn btn-default float-end" href="{% url 'admin:somesmart_review_change' review.id %}">Edit this review</a>
	{% endif %}
{% endblock content %}
{% block top-right-content %}{% endblock %}
{% block right-content %}
{% with review.edition.book as book %}
	{% include "somesmart/include_book_data.html" %}
	{% include "somesmart/include_recent_posts.html" %}
	{% include "somesmart/include_book_tags.html" %}
{% endwith %}
<div class="row">
	<h4 class="alert alert-secondary">Related Books</h4>
	<div id="related-books"></div>
</div>
{% endblock %}
{% block app.scripts %}
<script>
function get_related(book){
	$.ajax({
		type: "GET",
		url: '{% url "related-books" review.edition.book.id %}',
		success: function(data) {
			$('#related-books').append(data);
		}
	});
}
$(function() {
	jQuery(".tagManager").tagsManager({
		prefilled: [{% tags_for_object review.edition.book as prefilled_tags %}{% for tag in prefilled_tags %}"{{ tag.name }}"{% if not forloop.last %},{% endif %}{% endfor %}],
		preventSubmitOnEnter: true,
		typeahead: true,
		tagClass: 'badge rounded-pill bg-dark',
		typeaheadAjaxSource: '{% url "current-tags" %}', 
		typeaheadAjaxPolling: false
	});
	{% if request.user.id == 2 %}
	$('.save-tags').click(function() {
		var new_tags = $('input[name=hidden-tagsjax]').val();
		$.ajax({
			url: '{% url "save-tags" review.edition.book.id %}',
			type: 'POST',
			data: {
			new_tags: new_tags,
			csrfmiddlewaretoken: '{{ csrf_token }}'
			},
			success:function (data) {
			if (data == '1')
			{
				$("#tags-status")
				.addClass("success")
				.html("<div class='alert alert-success'>Your keywords have been saved. <a href='#'' class='close' data-dismiss='alert'>×</a></div>").fadeIn('slow');
			}
			else
			{
				$("#tags-status").addClass("error").html("Error, data could not be saved. Invalid keywords: " + data + " <a href='#'' class='close' data-dismiss='alert'>×</a>").fadeIn('slow');
			}
			}
		});
	});
	{% endif %}
	get_related();
});
</script>
{% endblock %}

templates/somesmart/base_search_tags.html
{% extends "somesmart/base.html" %}
{% load static %}

{% block title %}Tag Search{% endblock title %}
{% block top-content %}
<div class="row">
	<div class="col-md-8 col-lg-offset-2 random-quote"></div>
	<div class="col-md-2"></div>
</div>
<div class="row">
	<div class="col-md-10 col-lg-offset-1">
		<h3>Tag search results</h3>
		{% if book_list %}
			{% for book in book_list %}
				{% if forloop.counter0|divisibleby:"3" %}<div class="row">{% endif %}
					<div class="col-md-4">
						<div class="panel panel-default">
							<div class="panel-heading">
								<h5><center><a href="{% url 'book-view' book.id %}{{ book.title|slugify }}"> {{ book.title }}</a></center></h5>
							</div>
							{% for edition in book.edition_set.all %}
								{% if forloop.first %}
									<div class="panel-body">
										<center>{% if edition.cover %}<img src="{{ edition.cover.url }}" height="300px">{% else %}<img data-src="holder.js/200x300/auto" height="300px">{% endif %}</center>
									</div>
								{% endif %}
							{% endfor %}
						</div>
					</div>
				{% if forloop.last or forloop.counter|divisibleby:"3" %}</div>{% endif %}
			{% endfor %}
		{% else %}
			<p>No books found.</p>
		{% endif %}
	</div>
</div>
{% include "somesmart/include_pagination.html" %}
{% endblock %}
{% block top-right-content %}{% endblock top-right-content %}
{% block app.scripts %}
<script src="{% static 'js/holder/holder.js' %}"></script>
{% endblock %}