kbdb/urls.py
from django.conf.urls import *
from django.urls import include, re_path
from django.contrib.auth.decorators import login_required
from django.views.generic import DetailView, ListView, UpdateView, CreateView, DeleteView, TemplateView
from django.db.models import Count
from django.conf.urls.static import static
from kbdb.models import *
from kbdb import views as kbdb_views

urlpatterns = [
	re_path(r'^$', kbdb_views.LessonListView.as_view(), name='lesson-list'),
	re_path(r'^autocomplete/$',kbdb_views.autocomplete, name='kbdb-autocomplete'),
	re_path(r'^noresults/', TemplateView.as_view(template_name = 'somesmart/base_noresults.html'), name='no-results'),
	re_path(r'^round/(?P<pk>\d+)/', kbdb_views.RoundView.as_view(), name='round-view'),
	re_path(r'^round/$', kbdb_views.RoundListView.as_view(), name='round-list'),
	re_path(r'^lesson/(?P<pk>\d+)/', kbdb_views.LessonView.as_view(), name='lesson-view'),
	re_path(r'^lesson/add/', kbdb_views.LessonCreateView.as_view(), name='lesson-add'),
	re_path(r'^lesson/$', kbdb_views.LessonListView.as_view(), name='lesson-list'),
]

urls.py
from django.conf.urls import *
from django.views.generic import DetailView, ListView, UpdateView, CreateView, DeleteView
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from somesmart.models import *
from somesmart.views import *

admin.autodiscover()

urlpatterns = [
	url(r'^admin/', include(admin.site.urls)),
	url(r'^adventure/', include('adventure.urls')),
	url(r'^cashflow/', include('cashflow.urls')),
	url(r'^lotr/', include('lotr.urls')),
	url(r'^nature/', include('nature.urls')),
	url(r'^ornaments/', include('ornaments.urls')),
	url(r'^kbdb/', include('kbdb.urls')),
	url(r'^', include('somesmart.urls')),
] + staticfiles_urlpatterns() + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kbdb/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django_markdown.models import MarkdownField
import os

class RoundType(models.Model):
	""" The type of round that you are building """
	name = models.TextField(max_length=100)
	slug = models.SlugField()

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		if not self.id:
			self.slug = slugify(self.name)
		super(RoundType, self).save(*args, **kwargs)

class Round(models.Model):
	""" The name of the round and a full description if necessary """
	round_type = models.ForeignKey(RoundType, on_delete=models.CASCADE)
	name = models.CharField(max_length=100)
	description = MarkdownField(blank=True)

	def __str__(self):
		return self.name

class LessonType(models.Model):
	""" The type of lesson that you are conducting """
	name = models.TextField(max_length=100)
	slug = models.SlugField()

	def __str__(self):
		return self.name

	def save(self, *args, **kwargs):
		if not self.id:
			self.slug = slugify(self.name)
		super(LessonType, self).save(*args, **kwargs)

class Lesson(models.Model):
	""" The lesson you are conducting """
	date = models.DateField()
	lesson_type = models.ForeignKey(LessonType, on_delete=models.CASCADE)

	def __str__(self):
		return str(self.date)

class LessonRound(models.Model):
	""" The rounds that make up the lesson you are conducting """
	lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
	round_number = models.IntegerField()
	round = models.ForeignKey(Round, on_delete=models.CASCADE)

kbdb/forms.py
from django import forms
from django.forms import ModelForm
from django.forms.models import inlineformset_factory

from kbdb.models import *

class LessonForm(ModelForm):
	class Meta:
		model = Lesson
		fields = '__all__'

class LessonRoundForm(ModelForm):
	class Meta:
		model = LessonRound 
		fields = '__all__'

LessonRoundFormSet = inlineformset_factory(Lesson, LessonRound, form=LessonRoundForm)

kbdb/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponseRedirect, HttpResponse
import json
from django.db.models import Q, Count, Sum, Min, Max
from django.views.generic import DetailView, ListView, UpdateView, CreateView, FormView
from django.urls import reverse
from django.template import RequestContext
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator
from django.template.defaultfilters import slugify
from kbdb.models import *
from kbdb.forms import *
from decimal import *
from datetime import datetime
import urllib.request, urllib.error, urllib.parse
from xml.dom.minidom import parseString

# ****************************************************************** #
# ********************* autocomplete views ************************* #
# ****************************************************************** #

def autocomplete(request):
	if request.method == "GET":
		if 'term' in request.GET:
			value = request.GET['term']
			search = request.GET['search']
			results = []
			if search == "round":
				if len(value) > 0:
					rounds = Round.objects.filter(name__icontains=value)
					for rnd in rounds:
						data = {'id': rnd.id, 'label': rnd.name }
						results.append(data)
					json_results = json.dumps(results)
					return HttpResponse(json_results, content_type='application/json')
				else:
					return HttpResponseRedirect('/noresults/')
		else:
			return HttpResponseRedirect('/noresults/')

# ****************************************************************** #
# ************************** kbdb views **************************** #
# ****************************************************************** #

class RoundView(DetailView):
	template_name='kbdb/base_round.html'
	model = Round

class RoundListView(ListView):
	template_name='kbdb/base_round_list.html'
	queryset= Round.objects.select_related().order_by('name')
	context_object_name = 'round_list'
	paginate_by = 25

class LessonView(DetailView):
	template_name='kbdb/base_lesson.html'
	model = Lesson

class LessonListView(ListView):
	template_name='kbdb/base_lesson_list.html'
	queryset=Lesson.objects.select_related().order_by('-date')
	# queryset=Lesson.objects.select_related().order_by('-date').annotate(round_count=Count('lessonround__round'))
	context_object_name = 'lesson_list'
	paginate_by = 25

class LessonCreateView(CreateView):
	template_name = 'kbdb/base_lesson_create.html'
	model = Lesson
	form_class = LessonForm

	def form_valid (self, form):
		context = self.get_context_data()
		lessonround_form = context['lessonround_form']
		if listdetail_form.is_valid():
			return HttpResponseRedirect('/lesson/')
		else:
			return self.render(request, self.get_context_data(form=form))

	def form_invalid(self, form):
		return self.render(request, self.get_context_data(form=form))

	def get_context_data(self, **kwargs):
		context = super(LessonCreateView, self).get_context_data(**kwargs)
		if self.request.POST:
			context['lessonround_form'] = LessonRoundFormSet(self.request.POST, instance=self.object)
		else:
			context['lessonround_form'] = LessonRoundFormSet(instance=self.object)
		return context

templates/kbdb/base_lesson.html
{% extends "somesmart/base.html" %}
{% block title %}{{ lesson }}{% endblock title %}
{% block content %}
<a href="{% url 'lesson-list' %}" class="btn btn-default">Back To all Lessons</a>
	<h3>{{ lesson }} <small>: a {{ lesson.lesson_type }} Lesson</small></h3>
	{# Add information here about all the rounds in the lesson #}
	<table class="table table-striped">
		<thead>
			<tr>
				<th>#</th>
				<th>Round</th>
				<th>Round Type</th>
				<th>Times Used</th>
			</tr>
		</thead>
		<tbody>
			{% for round in lesson.lessonround_set.all %}
				<tr>
					<th scope="row">{{ round.round_number }}</th>
					<td><a href="{% url 'round-view' round.round.id %}">{{ round.round }}</a></td>
					<td>{{ round.round.round_type }}</td>
					<td>{# {{ round_count }} #}</td>
				</tr>
			{% endfor %}
		</tbody>
	</table>
{% endblock content %}
{% block top-right-content %}{% endblock top-right-content %}
{% block right-content %}
	<div class="col-md-10 col-lg-offset-1">
		{% include "somesmart/include_contact.html" %}
	</div>
{% endblock %}

templates/kbdb/base_lesson_create.html
{% extends "somesmart/base.html" %}
{% load static %}
{% block app.css %}
<link rel="stylesheet" href="{% static "somesmart/css/colorbox/colorbox.css" %}">
{% endblock %}
{% block title %}Create Your Lesson{% endblock title %}
{% block app.scripts %}
<script type="text/javascript" src="https://somesmart.com/static/js/colorbox/jquery.colorbox.js"></script>
<script type="text/javascript">
$(function() {
		$("#selector").autocomplete({
			source: "{% url 'kbdb-autocomplete' %}?search=round",
			minLength: 3,
			select: function(event, ui) {
				$('#round_id').val(ui.item.id);
				$('#name').val(ui.item.label);
			}
		});
		var rowID;
		//set the starting value at 0
		rowID = 0;

		$("#add_round").click(function(e){ 
			//get the autocomplete values for use below
			var round_id = $('#round_id').val();
			var name = $('#name').val();
			//generate the new formset html
			var htmlData = "<tr><th><label for='id_lessonrounds-" + rowID +"-round'>Round:</label></th><td><input type='hidden' name='lessonrounds-" + rowID + "-round' id='id_lessonrounds-" + rowID + "-round' value='" + round_id + "'>" + name + "</td><td><label for='id_lessonrounds-" + rowID + "-DELETE'>Delete:</label><input type='checkbox' name='lessonrounds-" + rowID + "-DELETE' id='id_lessonrounds-" + rowID + "-DELETE' /><input type='hidden' name='lessonrounds-" + rowID + "-lesson' id='id_lessonrounds-" + rowID + "-lesson' /></td></tr>";
			$.find('#lessonround_form').append(htmlData);
			//increment the formid
			rowID++;
			//update the total forms amount
			$('#id_lessonrounds-TOTAL_FORMS').val(rowID);
			//empty the selector field and focus on it
			$('#selector').val('');
			$('#selector').focus();
			//stops the form from refreshing the page like it normally would.
			e.preventDefault();
		}); 
		$(".ajax").colorbox({height:"650px", width:"565px", iframe:true, onClosed:function(){ 
			parent.updateOption({{ user.id }});
			}
		});
	});
</script>
{% endblock %}

{% if perms.kbdb.add_lesson %}
	{% block content %}
		<h3>Create your new lesson</h3>
		<p>Note that while only you will be able to edit this lesson in the future, others will be able to pull it up and compare their own lessons.</p>
		<form action="" method="post" class="form-horizontal">
			<div class="form-row">
				{{ form.name.label_tag }}
				{{ form.name }}
				{{ form.name.errors }}
			</div>
		<table class="table">
			{{ form.as_table }}
		</table>
		<fieldset class="">
			<legend>Rounds in the Lesson:</legend>
			<span class="col-md-10"><input class="form-control" type="text" id="selector" name="selector" /></span>
			<input type="hidden" id="round_id" name="round_id" />
			<input type="hidden" id="name" name="name" />
			<input type="submit" value="Add Round" class="btn btn-default" id="add_round" />
			<input type="hidden" name="lessonrounds-TOTAL_FORMS" value="0" id="id_lessonrounds-TOTAL_FORMS" /><input type="hidden" name="lessonrounds-INITIAL_FORMS" value="0" id="id_lessonrounds-INITIAL_FORMS" /><input type="hidden" name="lessonrounds-MAX_NUM_FORMS" id="id_lessonrounds-MAX_NUM_FORMS" />
			<table class="table table-hover lessonround_form" id="lessonround_form">
			</table>
		</fieldset>
		<div class="submit-row">
			{% csrf_token %}
			<input type="submit" value="Create Lesson" class="submit btn btn-default pull-right" />
		</div>
		</form>
	{% endblock content %}
{% else %}
	<p>I'm sorry, you are not authorized to update this lesson. Please contact the administrator for more information.</p>
{% endif %}
{% block top-right-content %}{% endblock %}
{% block right-content %}
	{% include "somesmart/include_book_data.html" %}
	{% include "somesmart/include_recent_posts.html" %}
{% endblock %}

templates/kbdb/base_lesson_list.html
{% extends "somesmart/base.html" %}
{% block title %}Lessons{% endblock title %}
{% block content %}
	<h3>Lessons</h3>
	<ul>
		{% for lesson in lesson_list %}
			<li><a href="{% url 'lesson-view' lesson.id %}">{{ lesson }}</a>: {{ lesson.date }}</li>
			{# Add information here about the number of rounds in the lesson? #}
		{% endfor %}
	</ul>
{% endblock content %}
{% block top-right-content %}{% endblock top-right-content %}
{% block right-content %}
	<div class="col-md-10 col-lg-offset-1">
		{% include "somesmart/include_contact.html" %}
	</div>
{% endblock %}

templates/kbdb/base_round.html
{% extends "somesmart/base.html" %}
{% block title %}{{ Round }}{% endblock title %}
{% block content %}
<a href="{% url 'round-list' %}" class="btn btn-default">Back To all Rounds</a>
	<h3>{{ round }} <small>: a {{ round.round_type }} Round</small></h3>
	{# Add information here about the last time it was used in a lesson and the # of times it has been used #}
	{# Add information here about all the lessons it has been used in #}
{% endblock content %}
{% block top-right-content %}{% endblock top-right-content %}
{% block right-content %}
	<div class="col-md-10 col-lg-offset-1">
		{% include "somesmart/include_contact.html" %}
	</div>
{% endblock %}

templates/kbdb/base_round_list.html
{% extends "somesmart/base.html" %}
{% block title %}Rounds{% endblock title %}
{% block content %}
	<h3>Rounds</h3>
	<ul>
		{% for round in round_list %}
			<li><a href="{% url 'round-view' round.id %}">{{ round }}</a>: {{ round.round_type }}</li>
			{# Add information here about the last time it was used in a lesson and the # of times it has been used #}
		{% endfor %}
	</ul>
{% endblock content %}
{% block top-right-content %}{% endblock top-right-content %}
{% block right-content %}
	<div class="col-md-10 col-lg-offset-1">
		{% include "somesmart/include_contact.html" %}
	</div>
{% endblock %}